@startuml

title __LOGIC's Class Diagram__\n

  namespace logic {
    class logic.CollisionLogic {
        {static} - blocks : ArrayList<MapObject>
        {static} - players : Player[]
        {static} + collided()
        {static} + collidedBottom()
        {static} + collidedBottomWithBlock()
        {static} + collidedBottomWithPlayer()
        {static} + collidedLeft()
        {static} + collidedLeftWithBlock()
        {static} + collidedRight()
        {static} + collidedRightWithBlock()
        {static} + collidedTop()
        {static} + collidedTopWithBlock()
        {static} + collidedTopWithPlayer()
        {static} + collidedWithBlock()
        {static} + setBlocks()
        {static} + setPlayers()
        {static} + willCollideHorizontallyWithBlock()
        {static} + willCollideHorizontallyWithObject()
        {static} + willCollideHorizontallyWithPlayer()
        {static} + willCollideVerticallyWithBlock()
        {static} + willCollideVerticallyWithObject()
        {static} + willCollideVerticallyWithPlayer()
        {static} - intersectsOnHorizontalPlane()
        {static} - intersectsOnVerticalPlane()
    }
  }
  

  namespace logic {
    class logic.GunLogic {
        {static} + AK : byte
        {static} + AUTO : byte
        {static} + BUCKSHOT : byte
        {static} + BURST : byte
        {static} + FAMAS : byte
        {static} + GLOCK : byte
        {static} + HEAVY_BULLET : byte
        {static} + LIGHT_BULLET : byte
        {static} + MP5 : byte
        {static} + REVOLVER : byte
        {static} + SAIGA : byte
        {static} + SEMI : byte
        {static} + SHOTGUN : byte
        {static} + SHOTGUN_BULLET : byte
        {static} + SNIPER : byte
        {static} + STANDARD_BULLET : byte
        {static} + UZI : byte
        {static} - BULLET_TYPES : byte[]
        {static} - BURST_DELAY : int
        {static} - DAMAGE_PER_HIT : byte[]
        {static} - FIRE_MODES : byte[]
        {static} - MAG_CAPACITY : byte[]
        {static} - RANGE : int[]
        {static} - RELATIVE_BULLET_EXIT_POINT_Y : float[]
        {static} - RELATIVE_X_POSITION : float[]
        {static} - RELOAD_TIME_MILLIS : int[]
        {static} - SHOT_DELAY_MILLIS : int[]
        {static} - X_VELS : float[]
        {static} + generateScaledProperties()
        {static} + getBulletTypes()
        {static} + getBurstDelay()
        {static} + getDamagePerHit()
        {static} + getDelayBetweenShots()
        {static} + getFireMode()
        {static} + getMagCapacity()
        {static} + getRange()
        {static} + getRelativeBulletExitPointY()
        {static} + getRelativeXPosition()
        {static} + getReloadTime()
        {static} + getxVel()
        {static} + getyVel()
    }
  }
  

  namespace logic {
    class logic.PlayerLogic {
        {static} + PLAYER1 : byte
        {static} + PLAYER2 : byte
        {static} - MAX_X_VEL : float
        {static} - MIN_X_VEL : float
        {static} - X_ACCELERATION : float
        {static} - Y_ACCELERATION : float
        {static} - Y_VEL : float
        {static} - relativeLeftHandX : float[]
        {static} - relativeLeftHandY : float[]
        {static} - relativeRightHandX : float[]
        {static} - relativeRightHandY : float[]
        {static} + generateScaledProperties()
        {static} + getMaxXVel()
        {static} + getMinXVel()
        {static} + getRelativeLeftHandX()
        {static} + getRelativeLeftHandY()
        {static} + getRelativeRightHandX()
        {static} + getRelativeRightHandY()
        {static} + getxAcceleration()
        {static} + getyAcceleration()
        {static} + getyVel()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
